# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('private', models.IntegerField()),
                ('langmask', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'contest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'contest_problem',
                'managed': False,
            },
        ),
    ]
