# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldUser',
            fields=[
                ('user_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('submit', models.IntegerField(blank=True, null=True)),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('defunct', models.CharField(max_length=1)),
                ('ip', models.CharField(max_length=20)),
                ('accesstime', models.DateTimeField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('language', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('reg_time', models.DateTimeField(blank=True, null=True)),
                ('nick', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
