# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompileInfo',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compileinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RunTimeInfo',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'runtimeinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=48)),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('in_date', models.DateTimeField()),
                ('result', models.SmallIntegerField()),
                ('language', models.IntegerField()),
                ('ip', models.CharField(max_length=15)),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('valid', models.IntegerField()),
                ('num', models.IntegerField()),
                ('code_length', models.IntegerField()),
                ('judgetime', models.DateTimeField(blank=True, null=True)),
                ('pass_rate', models.DecimalField(decimal_places=6, max_digits=7)),
                ('lint_error', models.IntegerField()),
                ('judger', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'solution',
                'managed': False,
            },
        ),
    ]
