# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField(max_length=0)),
                ('status', models.IntegerField()),
                ('top_level', models.IntegerField()),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField()),
                ('author_id', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'topic',
                'managed': False,
            },
        ),
    ]
