# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OjSourceCode',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source_code_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('solution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
            ],
            options={
                'db_table': 'source_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlySourceCode',
            fields=[
                ('uuid', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=255)),
                ('source', models.TextField(blank=True, null=True)),
                ('lexer', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'only_source_code',
            },
        ),
    ]
